apiVersion: witboost.com/v2
kind: EditTemplate
metadata:
  name: edit-google-workload-pyspark-template.1
  title: Edit Google Dataproc PySpark Workload
  description: Edit a Google Dataproc PySpark workload
  tags:
    - edit
    - cloud
    - google
    - dataproc
    - workload
    - pyspark
spec:
  owner: agilelab
  useCaseTemplateId:
    - urn:dmb:utm:google-dataproc-workload-template:0.0.0
  parameters:
    - title: Google Dataproc PySpark Workflow Template
      description: |-
        Use this template to edit a Google Dataproc PySpark workflow template and define PySpark jobs in your system.
    - title: Basic component information
      description: Basic information for this component.
      required:
        - description
      properties:
        name:
          title: Name
          type: string
          description: A human readable name used for display purposes.
          ui:disabled: true
        description:
          title: Description
          type: string
          description: Detailed explanation about the function and the meaning of the
            PySpark job.
        dataproduct:
          title: Data Product
          type: string
          description: Data Product this Dataproc workload belongs to.
          ui:disabled: true
          ui:field: EntitySearchPicker
          ui:options:
            multiSelection: false
            entities:
              - type: System
                displayField: '{{spec.mesh.name}}'
                returnField: ref
                filter:
                  practiceShaper:
                    kind: instanceOf
                    instanceOf:
                      - systemtype:default/dataproduct
                userFilters:
                  - search
                  - domain
                  - type
                columns:
                  - name: name
                    path: '{{spec.mesh.name}}'
                  - name: owner
                    path: '{{spec.owner}}'
        identifier:
          title: Identifier
          type: string
          description: Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:disabled: true
        owner:
          title: Owner
          type: string
          description: LDAP user/group that owns the data product.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:disabled: true
          ui:options:
            allowArbitraryValues: false
    - title: Artifact information
      description: |
        Fill out the information about the Artifact to be referenced in the workflow template.
      required:
        - gcsInternalStorageAreaId
      properties:
        artifactName:
          title: Artifact Name
          type: string
          description: |
            The name of the artifact to be referenced. Leave empty to use the default name composed by the identifier of the component.
        gcsInternalStorageAreaId:
          title: GCS Internal Storage Area
          type: string
          description: GCS Storage area that will be used by Dataproc as internal bucket.
          ui:field: EntityRelationsPicker
          ui:filters:
            - key: spec.type
              value: storage
            - key: spec.mesh.technology
              value: GCS
          ui:fieldName: dataproduct
          relation: hasPart
    - title: Provide Job information
      description: |
        Fill out the information about the job you are passing to the Dataproc Workflow template.
      required:
        - baseImage
      properties:
        baseImage:
          title: Starting base image
          type: string
          description: The Linux image to start with.
        mainPythonFile:
          title: Main Python Class
          type: string
          description: The relative path where to find the main Python file for the PySpark job, e.g. "path/to/main.py".
        additionalPythonFiles:
          title: Additional Python Classes
          type: array
          items:
            type: string
          description: The relative path to the additional Python files that can be called by the main class, e.g. "path/to/additional.py".
        jarFiles:
          title: Jar Files
          description: |
            The relative path to the JAR files to include in the Workflow template, e.g. "path/to/jarfile.jar".
          type: array
          items:
            type: string
        args:
          title: Job Arguments
          description: The arguments to pass to the main Python class.
          type: array
          items:
            type: string
    - title: Environment Variables
      environmentParameters: true
      properties:
        project:
          title: Project ID
          type: string
          description: |
            Google Cloud project ID where the Workflow Template will be created.
        region:
          title: Region
          type: string
          description: |
            Region where the Workflow Template will be created. Example: "europe-west1".
        serviceAccount:
          title: Service Account
          type: string
          description: Service account email used to create the Dataproc cluster.
        timeToLive:
          title: Time to Live
          type: number
          description: Time before the job is killed (Minutes).
        artifactVersion:
          title: Artifact Version
          type: string
          description: The version of the Artifact to be used.
        masterConfigs:
          title: Master Nodes Configuration
          type: object
          properties:
            machineType:
              type: string
              description: Machine type. Refer to
                https://cloud.google.com/dataproc/docs/concepts/compute/supported-machine-types
              title: Machine Type
              enum:
                - n2-standard-2
                - n2-standard-4
                - n2-standard-8
                - n2-standard-16
                - n2-standard-32
                - e2-standard-2
                - e2-standard-4
                - e2-standard-8
                - e2-medium
                - e2-highmem-2
                - e2-highmem-4
                - n2-highmem-2
                - n2-highmem-4
                - n2-highmem-8
                - n2-highmem-16
                - n2-highmem-32
            primaryDiskSizeGB:
              title: Primary Disk Size
              type: number
              description: Primary Disk Size (GB). The primary disk contains the boot volume,
                system libraries and HDFS NameNode metadata.
            primaryDiskType:
              title: Primary Disk Type
              type: string
              description: Primary Disk Type. Storage space is much less expensive for a
                standard persistent disk. An SSD persistent disk is better for
                random IOPS or streaming throughput with low latency.
              enum:
                - Standard Persistent Disk
                - SSD Persistent Disk
            numLocalSSD:
              title: Number of local SSD
              type: number
              description: Number of local SSD (max 8). Each SSD provides 375 GB of fast local
                storage. If one or more SSDs are attached, the HDFS data blocks and
                local execution directories are spread across these disks. HDFS does
                not run on preemptible nodes.
            count:
              title: Number of Nodes
              type: number
              description: |
                The number of master nodes in the cluster. The default is 1.
        workerConfigs:
          title: Worker Nodes Configuration
          type: object
          properties:
            machineType:
              title: Machine Type
              type: string
              description: Machine type. Refer to
                https://cloud.google.com/dataproc/docs/concepts/compute/supported-machine-types
              enum:
                - n2-standard-2
                - n2-standard-4
                - n2-standard-8
                - n2-standard-16
                - n2-standard-32
                - e2-standard-2
                - e2-standard-4
                - e2-standard-8
                - e2-medium
                - e2-highmem-2
                - e2-highmem-4
                - n2-highmem-2
                - n2-highmem-4
                - n2-highmem-8
                - n2-highmem-16
                - n2-highmem-32
            primaryDiskSizeGB:
              title: Primary Disk Size
              type: number
              description: Primary Disk Size (GB). The primary disk contains the boot volume,
                system libraries and HDFS NameNode metadata.
            primaryDiskType:
              title: Primary Disk Type
              type: string
              description: Primary Disk Type. Storage space is much less expensive for a
                standard persistent disk. An SSD persistent disk is better for
                random IOPS or streaming throughput with low latency.
              enum:
                - Standard Persistent Disk
                - SSD Persistent Disk
            numLocalSSD:
              title: Number of local SSD
              type: number
              description: Number of local SSD (max 8). Each SSD provides 375 GB of fast local
                storage. If one or more SSDs are attached, the HDFS data blocks and
                local execution directories are spread across these disks. HDFS does
                not run on preemptible nodes.
            count:
              title: Number of Nodes
              type: number
              description: Number of workers in your cluster.
            secondaryWorkers:
              title: Secondary workers
              type: number
              description: Choose how many secondary workers you want to run. The default is 0, which means no secondary worker nodes are used.