apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: google-workload-pyspark-template.1
  title: Google Dataproc PySpark Workload
  description: Create a Google Dataproc PySpark workload
  tags:
    - cloud
    - google
    - dataproc
    - workload
    - pyspark
  mesh:
    icon: https://the-examples-book.com/tools/anvil/_images/pyspark.png
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  generates: componenttype:default/workload
  owner: agilelab
  type: workload
  parameters:
    - title: Google Dataproc PySpark Workflow Template
      description: |-
        This template allows you to create a Google Dataproc PySpark Workflow Template which can be used to define PySpark jobs in your System.
        After creation you can use the Editor Wizard to customize the component and add more details to the PySpark Workflow Template.
    - title: Basic component information
      description: Basic information for this component.
      required:
        - name
        - description
        - dataproduct
        - identifier
        - owner
      properties:
        name:
          title: Name
          type: string
          description: A human readable name used for display purposes.
          ui:field: EntityNamePicker
          default: PySpark Workload
          ui:options:
            allowArbitraryValues: true
        description:
          title: Description
          type: string
          description: Detailed explanation about the function and the meaning of the
            PySpark job.
          default: The PySpark workload used internally by this System.
        dataproduct:
          title: Data Product
          type: string
          description: Data Product this Dataproc workload belongs to.
          ui:field: EntitySearchPicker
          ui:options:
            multiSelection: false
            entities:
              - type: System
                displayField: '{{spec.mesh.name}}'
                returnField: ref
                filter:
                  practiceShaper:
                    kind: instanceOf
                    instanceOf:
                      - systemtype:default/dataproduct
                userFilters:
                  - search
                  - domain
                  - type
                columns:
                  - name: name
                    path: '{{spec.mesh.name}}'
                  - name: owner
                    path: '{{spec.owner}}'
        domain:
          title: Domain
          type: string
          description: Data Product domain
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.domain
          ui:widget: hidden
        identifier:
          title: Identifier
          type: string
          description: |
            Autogenerated from the information above. A unique identifier for the component. It will not be editable after creation and is a string composed of [a-zA-Z] separated by any of [-_].
          ui:field: ComponentIdentifierPicker
          ui:options:
            allowArbitraryValues: false
        owner:
          title: Owner
          type: string
          description: User/Group that owns the data product.
          ui:field: EntitySelectionPicker
          ui:fieldName: dataproduct
          ui:property: spec.owner
          ui:options:
            allowArbitraryValues: false
        additionalDependsOn:
          title: Additional Dependencies
          type: array
          description: |
            A Workload could depend on other components in the same System. This information will be used to deploy the components in such an order that their dependencies already exist.
          items:
            type: string
            ui:field: EntityRelationsPicker
            ui:fieldName: dataproduct
            relation: hasPart
            ui:options:
              allowArbitraryValues: false
        readsFrom:
          title: Reads from
          type: array
          ui:field: EntitySearchPicker
          ui:options:
            multiSelection: true
            entities:
              - type: Consumable
                displayField: '{{name}}'
                returnField: urn
                filter:
                  practiceShaper:
                    kind: canBeReadFrom
                    canBeReadFrom: componenttype:default/workload
                userFilters:
                  - search
                  - domain
                  - system
                  - environment
                columns:
                  - name: name
                    path: '{{name}}'
              - type: Resource
                displayName: Resource
                displayField: '{{spec.mesh.name}}'
                returnField: urn
                userFilters:
                  - search
                columns:
                  - name: name
                    path: '{{metadata.name}}'
    - title: Artifact information
      description: |
        Fill out the information about the Artifact to be referenced in the workflow template.
      required:
        - gcsInternalStorageAreaId
      properties:
        artifactName:
          title: Artifact Name
          type: string
          description: |
            The name of the artifact to be referenced. Leave empty to use the default name composed by the identifier of the component.
        gcsInternalStorageAreaId:
          title: GCS Internal Storage Area
          type: string
          description: GCS Storage area that will be used by Dataproc as internal bucket.
          ui:field: EntityRelationsPicker
          ui:filters:
            - key: spec.type
              value: storage
            - key: spec.mesh.technology
              value: Cloud
          ui:fieldName: dataproduct
          relation: hasPart
    - title: Provide Job information
      description: |
        Fill out the information about the job you are passing to the Dataproc Workflow template.
      required:
        - baseImage
        - mainPythonFile
      properties:
        baseImage:
          title: Starting base image
          type: string
          description: The Linux image to start with.
          default: 2.3-debian12
        mainPythonFile:
          title: Main Python File
          type: string
          description: The relative path where to find the main Python file for the PySpark job, e.g. "path/to/main.py".
          default: spark_app/main.py
        additionalPythonFiles:
          title: Additional Python Files
          type: array
          items:
            type: string
          description: |
            The relative path to the additional Python files that can be called by the main class, e.g. "path/to/additional.py".
        jarFiles:
          title: Jar Files
          description: |
            The relative path to the JAR files to include in the Workflow template, e.g. "path/to/jarfile.jar".
          type: array
          items:
            type: string
        args:
          title: Job Arguments
          description: The arguments to pass to the main Python file.
          type: array
          items:
            type: string
    - title: Google Cloud Deployment Configuration
      description: |
        Fill out the information about the target project, region and service accounts that will be used in the workflow.
      environmentParameters: true
      properties:
        project:
          title: Project ID
          type: string
          description: |
            Google Cloud project ID where the Workflow Template will be created.
        region:
          title: Region
          type: string
          description: |
            Region where the Workflow Template will be created. Example: "europe-west1".
        serviceAccount:
          title: Service Account
          type: string
          description: Service account email used to create the Dataproc cluster.
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          # Workload basic info
          name: '${{ parameters.name }}'
          fullyQualifiedName: '${{ parameters.name | trim }}'
          description: '${{ parameters.description }}'
          dataproduct: '${{ parameters.dataproduct }}'
          displayName: '${{ parameters.displayName }}'
          domain: '${{ parameters.domain }}'
          owner: '${{ parameters.owner }}'
          identifier: '${{ parameters.identifier }}'
          additionalDependsOn: ${{ parameters.additionalDependsOn }}
          readsFrom: ${{ parameters.readsFrom }}
          # Artifact info
          artifactName: '${{ parameters.artifactName }}'
          gcsInternalStorageAreaId: '${{ parameters.gcsInternalStorageAreaId }}'
          # Job info
          mainPythonFile: '${{ parameters.mainPythonFile }}'
          additionalPythonFiles: ${{ parameters.additionalPythonFiles }}
          jarFiles: ${{ parameters.jarFiles }}
          args: ${{ parameters.args }}
          imageVersion: '${{ parameters.baseImage }}'
          # GCP info
          project: '${{ parameters.project }}'
          region: '${{ parameters.region }}'
          serviceAccount: '${{ parameters.serviceAccount }}'
          # Template info
          repoUrl: &repoUrl 'gitlab.com?owner=AgileDMBSandbox%2F${{orgname}}%2Fmesh.repository%2F${{ parameters.domain | replace(r/domain:| |-/, "") }}%2F${{ parameters.dataproduct.split(".")[1] | replace(r/ |-/g, "") }}&repo=${{ parameters.name.split(" ") | join("") | lower }}'
          useCaseTemplateId: urn:dmb:utm:google-dataproc-workload-template:0.0.0
          infrastructureTemplateId: urn:dmb:itm:google-dataproc-workload-tech-adapter:0
          useCaseTemplateVersion: 0.0.0

    - id: publish
      name: Publish
      action: witboostMeshComponent:publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: This is ${{ parameters.name }}
        repoUrl: *repoUrl
        rootDirectory: .
        dataproduct: ${{ parameters.dataproduct }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
